title: "Réunion DEN"
format:
  revealjs:
    theme: [default, custom.scss]
author:
    - name: Laure Velez
    - name: Nicolas Barrier
    - name: Monique Simier
    - name: Julien Barde
    - name: Julien Lebranchu
    - name: Regis Hocde
    - name: Claudia Restrepo-Ortiz
