---
title: "Réunion DEN"
format:
  revealjs:
    theme: default
author:
    - name: Laure Velez
    - name: Nicolas Barrier
    - name: Monique Simier
    - name: Julien Barde
    - name: Julien Lebranchu
    - name: Regis Hocde
    - name: Claudia Restrepo-Ortiz
---

# Bilan Marbec Green

## Bilan Marbec Green

Claire Carre

# Resources numériques

## Resouces disponibles

L'UMR MARBEC dispose de plusieurs resources numériques pour le calcul et le stockage.

Pour en bénéficier, il faut:

-   Adherer au DEN
-   Faire la demande aupres de [Laure Velez et Nicolas Barrier](mailto:laure.velez@umontpellier.fr,nicolas.barrier@ird.fr)
-   Signer la charte du DEN (disponible sur le site MARBEC)

## Resources disponibles: calcul {.smaller}

| Resources  | Capacité                                                                        | Applications                       |
|------------------|------------------------------------|------------------|
| Marbec-GPU | 2 processeurs Xeon 8380 (40 coeurs / 80 threads),1,5 To de mémoire vive         | Calcul sur GPU, i.e. deep learning |
| Datarmor   | 11088 coeurs,128 Go de RAM                                                      | Calcul sur CPU                     |
| Meso\@LR   | 6 noeuds de 28 coeurs (bi processeurs Intel Xeon E5-2680 v4 2,4 Ghz (broadwell) | Calcul sur CPU                     |

: Resources de calcul {#tbl-calcul}

## Resources disponibles: stockage {.smaller}

| Resources   | Capacité                        | Applications                                              |
|------------------|-------------------|-----------------------------------|
| Marbec-Data | 448 To partagés                 | Stockage de données issues de projet                      |
| Datarmor    | 1 To/personne + 570.96 partagés | Stockage de données issues de calcul (sorties de modèles) |
| Meso\@LR    | 200 To partagés                 | Stockage de données issues de calcul (sorties de modèles) |

: Resources de stockage {#tbl-stockage}

## Resoucres disponibles: cloud {.smaller}

| Fournisseur                                      | Stockage                | Edition type Google Drive |
|------------------------|------------------------|-------------------------|
| [IRD](https://drive.ird.fr)[^1]                  | 5 To partages | Oui                       |
| [IFREMER](https://cloud.ifemer.fr)               | 5 Go/pers.              | Oui                       |
| [CNRS](https://mycore.core-cloud.net)[^2]        | 100 Go/pers.            | Oui                       |
| [RENATER](https://drive.demo.renater.fr)[^3]     | 20 Go/pers.             | Oui                       |
| [WIMI](https://www.wimi-teamwork.com/fr/)[^4] |                         |                           |
| [LEVIIA](https://www.leviia.com/)[^5]            |                         |                           |

: Resources de type Cloud {#tbl-cloud tbl-colwidths=\[10,30,30,30\]}

[^1]: Pour projets. Demande a faire aupres de Julien Barde
[^2]: Possibilite de demande d'un espace MARBEC
[^3]: Phase de test, pas operationnel
[^4]: Dropbox français/ \[Payant, hébergé en France\]
[^5]: Possibilité de présentation par la société (Claire Carré) Payant/hébergé en france